/* ZARRLEARN v1.5 - DATA KAMUS */

var kamusData = [
  { term: 'Bilangan Prima', def: 'Bilangan yang hanya bisa dibagi 1 dan dirinya sendiri. Contoh: 2, 3, 5, 7, 11', cat: 'matematika' },
  { term: 'FPB', def: 'Faktor Persekutuan Terbesar. Faktor terbesar yang sama dari dua bilangan atau lebih', cat: 'matematika' },
  { term: 'KPK', def: 'Kelipatan Persekutuan Terkecil. Kelipatan terkecil yang sama dari dua bilangan', cat: 'matematika' },
  { term: 'Pythagoras', def: 'Rumus a2 + b2 = c2 untuk segitiga siku-siku. a dan b sisi tegak, c sisi miring', cat: 'matematika' },
  { term: 'Gradien', def: 'Kemiringan garis. Dihitung dari perubahan y dibagi perubahan x (dy/dx)', cat: 'matematika' },
  { term: 'Faktorial', def: 'Perkalian berurutan dari n sampai 1. Contoh: 4! = 4x3x2x1 = 24', cat: 'matematika' },
  { term: 'Limit', def: 'Nilai yang didekati fungsi saat variabel mendekati nilai tertentu', cat: 'matematika' },
  { term: 'Turunan', def: 'Laju perubahan fungsi terhadap variabelnya. Dinotasikan dy/dx atau f(x)', cat: 'matematika' },
  { term: 'Integral', def: 'Kebalikan turunan. Menghitung luas di bawah kurva. Notasi: integral f(x) dx', cat: 'matematika' },
  { term: 'Logaritma', def: 'Eksponen yang diperlukan untuk menghasilkan bilangan. log 100 = 2 karena 10^2 = 100', cat: 'matematika' },
  { term: 'Trigonometri', def: 'Cabang matematika tentang sudut dan segitiga. Fungsi: sin, cos, tan', cat: 'matematika' },
  { term: 'Matriks', def: 'Susunan bilangan dalam baris dan kolom. Notasi: [a b; c d]', cat: 'matematika' },
  { term: 'Statistika', def: 'Ilmu tentang pengumpulan, analisis, dan penyajian data. Mean, median, modus', cat: 'matematika' },

  { term: 'Fotosintesis', def: 'Proses tumbuhan membuat makanan dari cahaya matahari, air, CO2. Hasil: glukosa + oksigen', cat: 'ipa' },
  { term: 'Mitokondria', def: 'Organel sel yang menghasilkan energi (ATP). Disebut the powerhouse of the cell', cat: 'ipa' },
  { term: 'Evaporasi', def: 'Perubahan air menjadi uap air karena panas matahari', cat: 'ipa' },
  { term: 'Kondensasi', def: 'Perubahan uap air menjadi titik air karena suhu dingin. Terbentuk awan', cat: 'ipa' },
  { term: 'Presipitasi', def: 'Turunnya air dari awan ke bumi dalam bentuk hujan, salju, atau es', cat: 'ipa' },
  { term: 'Gravitasi', def: 'Gaya tarik bumi terhadap benda. Nilai 9,8 m/s2', cat: 'ipa' },
  { term: 'Mitosis', def: 'Pembelahan sel yang menghasilkan 2 sel anak identik dengan induknya', cat: 'ipa' },
  { term: 'Meiosis', def: 'Pembelahan sel kelamin. Menghasilkan 4 sel dengan kromosom setengah', cat: 'ipa' },
  { term: 'Klorofil', def: 'Pigmen hijau pada daun yang menangkap cahaya untuk fotosintesis', cat: 'ipa' },
  { term: 'Respirasi', def: 'Proses pernapasan. Mengubah glukosa + oksigen menjadi energi + CO2 + H2O', cat: 'ipa' },

  { term: 'Newton', def: 'Satuan gaya dalam SI. Simbol N. 1 N = 1 kg m/s2', cat: 'fisika' },
  { term: 'Joule', def: 'Satuan energi dan usaha. Simbol J. 1 J = 1 N m', cat: 'fisika' },
  { term: 'Watt', def: 'Satuan daya. 1 watt = 1 joule per detik', cat: 'fisika' },
  { term: 'Momentum', def: 'Hasil kali massa dan kecepatan. p = m x v', cat: 'fisika' },
  { term: 'Inersia', def: 'Kecenderungan benda mempertahankan keadaan. Hukum Newton I', cat: 'fisika' },
  { term: 'Gaya Normal', def: 'Gaya tegak lurus permukaan yang menahan benda', cat: 'fisika' },
  { term: 'Energi Kinetik', def: 'Energi gerak benda. Rumus: Ek = 1/2 mv2', cat: 'fisika' },
  { term: 'Energi Potensial', def: 'Energi karena posisi benda. Rumus: Ep = mgh', cat: 'fisika' },
  { term: 'Hukum Ohm', def: 'Hubungan tegangan, arus, hambatan. V = I x R', cat: 'fisika' },
  { term: 'Medan Listrik', def: 'Daerah pengaruh gaya listrik. Satuan: N/C', cat: 'fisika' },

  { term: 'Atom', def: 'Unit terkecil materi yang masih memiliki sifat unsur. Terdiri dari proton, neutron, elektron', cat: 'kimia' },
  { term: 'Molekul', def: 'Gabungan dua atau lebih atom yang terikat secara kimia. Contoh: H2O, CO2', cat: 'kimia' },
  { term: 'Ion', def: 'Atom atau molekul bermuatan listrik. Kation (+), anion (-)', cat: 'kimia' },
  { term: 'Katalis', def: 'Zat yang mempercepat reaksi kimia tanpa ikut bereaksi', cat: 'kimia' },
  { term: 'pH', def: 'Tingkat keasaman larutan. Kurang 7 asam, 7 netral, lebih 7 basa', cat: 'kimia' },
  { term: 'Ikatan Kovalen', def: 'Ikatan dengan pemakaian elektron bersama. Contoh: H2O, CO2', cat: 'kimia' },
  { term: 'Ikatan Ionik', def: 'Ikatan akibat serah terima elektron. Contoh: NaCl, MgO', cat: 'kimia' },
  { term: 'Stoikiometri', def: 'Perhitungan kuantitatif dalam reaksi kimia. Menggunakan satuan mol', cat: 'kimia' },
  { term: 'Redoks', def: 'Reaksi reduksi dan oksidasi. Reduksi terima elektron, oksidasi lepas elektron', cat: 'kimia' },
  { term: 'Avogadro', def: 'Jumlah partikel dalam 1 mol = 6,02 x 10^23', cat: 'kimia' },

  { term: 'Sel', def: 'Unit terkecil kehidupan. Terdiri dari membran, sitoplasma, dan nukleus', cat: 'bio' },
  { term: 'DNA', def: 'Deoxyribonucleic Acid. Molekul pembawa informasi genetik berbentuk double helix', cat: 'bio' },
  { term: 'Gen', def: 'Bagian DNA yang mengkode sifat tertentu. Pewaris sifat dari orang tua', cat: 'bio' },
  { term: 'Kromosom', def: 'Kumpulan DNA yang memadat. Manusia memiliki 46 kromosom (23 pasang)', cat: 'bio' },
  { term: 'Ekosistem', def: 'Hubungan timbal balik makhluk hidup dengan lingkungannya', cat: 'bio' },
  { term: 'Evolusi', def: 'Perubahan makhluk hidup secara bertahap dalam waktu lama. Teori Darwin', cat: 'bio' },
  { term: 'Ribosom', def: 'Organel sel tempat sintesis protein', cat: 'bio' },
  { term: 'Vakuola', def: 'Organel penyimpanan sel. Pada tumbuhan berukuran besar', cat: 'bio' },

  { term: 'Sinonim', def: 'Persamaan kata. Contoh: pintar = cerdas = pandai', cat: 'bindo' },
  { term: 'Antonim', def: 'Lawan kata. Contoh: besar lawan kecil, tinggi lawan rendah', cat: 'bindo' },
  { term: 'Konjungsi', def: 'Kata penghubung. Contoh: dan, atau, tetapi, karena, meskipun', cat: 'bindo' },
  { term: 'Pantun', def: 'Puisi lama 4 baris, bersajak a-b-a-b. Baris 1-2 sampiran, 3-4 isi', cat: 'bindo' },
  { term: 'Syair', def: 'Puisi lama 4 baris, bersajak a-a-a-a. Berisi cerita atau nasihat', cat: 'bindo' },
  { term: 'Metafora', def: 'Gaya bahasa perbandingan langsung. Contoh: wajahnya bulan', cat: 'bindo' },
  { term: 'Personifikasi', def: 'Gaya bahasa mengumpamakan benda mati seperti hidup. Contoh: angin berbisik', cat: 'bindo' },
  { term: 'Hiperbola', def: 'Gaya bahasa melebih-lebihkan. Contoh: suaranya menggelegar', cat: 'bindo' },
  { term: 'Protagonis', def: 'Tokoh utama dalam cerita yang bersifat baik', cat: 'bindo' },
  { term: 'Antagonis', def: 'Tokoh penentang protagonis, biasanya bersifat jahat', cat: 'bindo' },

  { term: 'Verb', def: 'Kata kerja. Contoh: eat, run, sleep, write', cat: 'bing' },
  { term: 'Noun', def: 'Kata benda. Contoh: book, table, cat, house', cat: 'bing' },
  { term: 'Adjective', def: 'Kata sifat. Contoh: beautiful, tall, smart, happy', cat: 'bing' },
  { term: 'Adverb', def: 'Kata keterangan. Contoh: quickly, well, slowly', cat: 'bing' },
  { term: 'Present Tense', def: 'Waktu sekarang. Contoh: I eat rice every day', cat: 'bing' },
  { term: 'Past Tense', def: 'Waktu lampau. Contoh: I ate rice yesterday', cat: 'bing' },
  { term: 'Future Tense', def: 'Waktu akan datang. Contoh: I will eat rice tomorrow', cat: 'bing' },
  { term: 'Present Perfect', def: 'Telah dilakukan. Rumus: have/has + V3. Contoh: I have eaten', cat: 'bing' },
  { term: 'Past Continuous', def: 'Sedang dilakukan di masa lalu. Rumus: was/were + V-ing', cat: 'bing' },
  { term: 'Passive Voice', def: 'Kalimat pasif. Rumus: be + V3. Contoh: The book is read by Budi', cat: 'bing' },

  { term: 'ASEAN', def: 'Association of Southeast Asian Nations. Berdiri 8 Agustus 1967 di Bangkok', cat: 'ips' },
  { term: 'Proklamasi', def: 'Pernyataan kemerdekaan Indonesia. Dibacakan Soekarno 17 Agustus 1945', cat: 'ips' },
  { term: 'Reformasi', def: 'Perubahan sistem pemerintahan Indonesia tahun 1998. Soeharto turun', cat: 'ips' },
  { term: 'Globalisasi', def: 'Proses masuknya pengaruh global ke suatu negara. Bidang ekonomi, budaya, teknologi', cat: 'ips' },
  { term: 'APEC', def: 'Asia-Pacific Economic Cooperation. Kerja sama ekonomi Asia Pasifik', cat: 'ips' },
  { term: 'OPEC', def: 'Organization of Petroleum Exporting Countries. Negara pengekspor minyak', cat: 'ips' },
  { term: 'PBB', def: 'Perserikatan Bangsa-Bangsa. Berdiri 24 Oktober 1945. Markas New York', cat: 'ips' },
  { term: 'NATO', def: 'North Atlantic Treaty Organization. Aliansi militer negara Barat', cat: 'ips' }
];
